config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  get '/history', to: 'home#history'

  resources :log_games, except: [:show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log_game.rb
class LogGame < ApplicationRecord

  belongs_to :user
  belongs_to :opponent, class_name: 'User'

  validates :opponent_id, :user_id, :user_score, :opponent_score, :date_played, presence: true

  def score(current_user)
    score = [user_score, opponent_score]
    opponent_is?(current_user) ? score.reverse.join('-') : score.join('-')
  end

  def result(current_user)
    score = [user_score, opponent_score]
    result = opponent_is?(current_user) ? score.reverse : score
    result[0] > result[1] ? 'W' : 'L'
  end

  def set_opponent(current_user)
    obj = opponent_is?(current_user) ? user : opponent
    obj.full_name
  end

  private

    def opponent_is?(user)
      opponent_id == user.id
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :trackable, :validatable

  has_many :log_games_as_user, class_name: 'LogGame', foreign_key: 'user_id', dependent: :destroy
  has_many :log_games_as_opponent, class_name: 'LogGame', foreign_key: 'opponent_id', dependent: :destroy

  validates :first_name, :last_name, presence: true

  def full_name
    [first_name, last_name].join(' ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    registration_params = [:last_name, :first_name, :email, :password, :password_confirmation, :remember_me]
    update_params = [:last_name, :first_name, :email, :password, :password_confirmation, :current_password]
    devise_parameter_sanitizer.permit(:sign_up){ |u| u.permit(registration_params) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(update_params)}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def history
  end

end

app/controllers/log_games_controller.rb
class LogGamesController < ApplicationController
  before_action :set_log_game, only: [:show, :edit, :update, :destroy]

  def index
    @log_games = LogGame.preload(:user, :opponent).where('log_games.opponent_id = ? or log_games.user_id = ? ', current_user.id, current_user.id)

  end

  def new
    @log_game = current_user.log_games_as_user.build
    @users = User.where.not(id: current_user.id).collect { |u| [ u.full_name, u.id ] }
  end

  def edit
  end

  def create
    log_game = current_user.log_games_as_user.build(log_game_params)
    if log_game.save
      redirect_to log_games_path, notice: 'Log game was successfully created.'
    else
      render :new
    end
  end

  def update
    if @log_game.update(log_game_params)
      redirect_to @log_game, notice: 'Log game was successfully updated.'
    else
      render :edit
    end
  end

  # def destroy
  #   @log_game.destroy
  #   redirect_to log_games_url, notice: 'Log game was successfully destroyed.'
  # end

  private
    def set_log_game
      @log_game = LogGame.find(params[:id])
    end

    def log_game_params
      params.require(:log_game).permit(:first_name, :last_name, :opponent_id, :user_score, :opponent_score, :date_played)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/log_games_helper.rb
module LogGamesHelper
end

app/views/home/history.html.erb
<h1 class='page-header'>History</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= image_tag('history.png') %>

app/views/home/index.html.erb
<h1 class='page-header'>Leaderboard</h1>

<div class="alert alert-warning" role="alert">This is a sample page.</div>

<%= image_tag('leaderboard.png') %>

app/views/home/log.html.erb
<h1 class='page-header'>Log Game</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= image_tag('log_game.png') %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pingpong</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= link_to 'Log Game', new_log_game_path, class: 'btn btn-success navbar-btn' %>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Leadboard', root_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'History', log_games_path %></li>
          <li><%= link_to current_user.email, '#' %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pingpong Leaderboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", integrity: "sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js", integrity: "sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>

app/views/log_games/_form.html.haml
= form_for log_game, html: { class: 'form-horizontal candidate-form' } do |f|
  - if log_game.errors.any?
    #error_explanation
      %h2
        = pluralize(log_game.errors.count, "error")
        prohibited this log_game from being saved:
      %ul
        - log_game.errors.full_messages.each do |message|
          %li= message

  .form-group
    .col-sm-3.control-label
      = f.label :date_played
    .col-sm-3
      = f.date_select :date_played, { order: [:month, :day, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: Date.today.year, end_year: Date.today.year - 100 }, required: true, class: 'form-control'
  .form-group
    .col-sm-3.control-label
      = f.label :opponent_id
    .col-sm-3
      = f.select :opponent_id, users, { :include_blank => '-- Select One --' }, required: true, class: 'form-control'
  .form-group
    .col-sm-3.control-label
      = f.label :user_score, 'Your score'
    .col-sm-3
      = f.number_field :user_score, required: true, class: 'form-control'
  .form-group
    .col-sm-3.control-label
      = f.label :opponent_score, 'Their score'
    .col-sm-3
      = f.number_field :opponent_score, required: true, class: 'form-control'

  %hr
  .form-group
    .col-sm-2
      = f.submit log_game.new_record? ? 'Save' : 'Update', class: 'btn btn-primary'
      = link_to 'Back', log_games_path, class: 'btn btn-default'

app/views/log_games/edit.html.haml
%h1 Editing Log Game
= render 'form', log_game: @log_game, users: @users
= link_to 'Show', @log_game

app/views/log_games/index.html.haml
%p#notice= notice
%h1 History

.container
  .row
    .col-md-12
      %table.table.table-hover.table-bordered.table-striped
        %thead
          %tr.table_head_color
            %th id
            %th Date
            %th Opponent
            %th Score
            %th Result
        %tbody
          - @log_games.each do |lg|
            %tr
              %td= lg.id
              %td= lg.date_played.strftime('%b %e')
              %td= lg.set_opponent(current_user)
              %td= lg.score(current_user)
              %td= lg.result(current_user)
%br/
= link_to 'New Log Game', new_log_game_path, class: 'btn btn-info'

app/views/log_games/new.html.haml
%h1 New Log Game
= render 'form', log_game: @log_game, users: @users